export default defineAppConfig({
  shadcnDocs: {
    site: {
      name: 'shadcn-flutter',
      description: 'Beautifully designed Flutter components powered by Flutterwind. Accessible. Customizable. Open Source.',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
      ogImageColor: 'light',
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.5,
    },
    banner: {
      enable: false,
      showClose: true,
      content: 'Welcome to **shadcn-flutter**',
      to: 'https://github.com/flutterwind/shadcn_flutter',
      target: '_blank',
      border: true,
    },
    header: {
      title: 'shadcn-flutter',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      darkModeToggle: true,
      nav: [{
        title: 'Docs',
        links: [{
          title: 'Getting Started',
          to: '/getting-started/introduction',
          description: 'Start building Flutter UIs with shadcn-flutter.',
          icon: 'lucide:rocket',
        }, {
          title: 'Components',
          to: '/components/button',
          description: 'Explore all available Flutter components.',
          icon: 'lucide:box',
        }],
      }, {
        title: 'Libraries',
        links: [{
          title: 'Flutterwind',
          to: 'https://flutterwind.brighthustle.in',
          description: 'The Tailwind-style utility engine powering shadcn-flutter.',
          icon: 'lucide:wind',
        }],
      }],
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/flutterwind/shadcn_flutter',
        target: '_blank',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:copy',
      editLink: {
        enable: true,
        pattern: 'https://github.com/flutterwind/shadcn_flutter/edit/main/docs/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter', 'toc'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
        'dart': 'logos:dart',
        'flutter': 'logos:flutter',
        'pubspec.yaml': 'vscode-icons:file-type-yaml',
        'analysis_options.yaml': 'vscode-icons:file-type-yaml',
        'tailwind.config.yaml': 'vscode-icons:file-type-yaml',
      },
    },
    footer: {
      credits: 'Made with ❤️ by [**Kumar Yash**](https://github.com/CodeSyncr/)',
      links: [{
        icon: 'lucide:heart',
        title: 'Sponsor',
        to: 'https://github.com/sponsors/CodeSyncr',
        target: '_blank',
      }, {
        icon: 'lucide:twitter',
        to: 'https://x.com/codesyncr',
        target: '_blank',
      }, {
        icon: 'lucide-lab:butterfly',
        to: 'https://www.instagram.com/unreal_cto',
        target: '_blank',
      }, {
        icon: 'lucide:github',
        to: 'https://github.com/CodeSyncr',
        target: '_blank',
      }],
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: 'On This Page',
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/flutterwind/shadcn_flutter',
        target: '_blank',
        showLinkIcon: true,
      }, {
        title: 'Create Issues',
        icon: 'lucide:circle-dot',
        to: 'https://github.com/flutterwind/shadcn_flutter/issues',
        target: '_blank',
        showLinkIcon: true,
      }],
      carbonAds: {
        enable: false,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: 'CW7ITKJN',
        placement: 'shadcn-docs-nuxtvercelapp',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
    },
    data: {},
  },
});
